<div class="column grid_1">
    <nav>
        <ul>
            <li><a href="#" title="list contacts"><img src="ui/img/ico_contact_list.png" alt="list contacts"></a></li>
            <?php if ($row['phone']) { ?>
            <li><a href="tel:<?= $row['phone'] ?>" title="call phone"><img src="ui/img/ico_contact_phone.png" alt="call phone"></a></li>
            <?php } ?>
            <?php if ($row['mobile']) { ?>
            <li><a href="tel:<?= $row['mobile'] ?>" title="call mobile"><img src="ui/img/ico_contact_mobile.png" alt="call mobile"></a></li>
            <?php } ?>
            <?php if ($row['email']) { ?>
            <li><a href="mailto:<?= $row['email'] ?>" title="write email"><img src="ui/img/ico_contact_mail.png" alt="write email"></a></li>
            <?php } ?>
            <?php if ($row['id']) { ?>
            <li><a href="vcard/<?= $row['id'] ?>" title="download vCard"><img src="ui/img/ico_contact_vcard.png" alt="download vCard"></a></li>
            <li><a href="api/<?= $row['id'] ?>" title="get REST"><img src="ui/img/ico_contact_rest.png" alt="get REST"></a></li>
            <?php } ?>
        </ul>
    </nav>
</div>

<form class="column grid_11 contact" action="form/<?= $row['id'] ?>" method="POST">
    <table>
        <tr>
            <th class="label">key</th>
            <th>value</th>
        </tr>
        <?php foreach ($row as $name => $value) { ?>
        <tr>
            <td class="label"><label for="<?= $name ?>"><?= $name ?></label></td>
            <td class="input"><input type="text" id="<?= $name ?>" name="row[<?= $name ?>]" value="<?= $value ?>"></td>
        </tr>
        <?php } ?>
    </table>
    <input type="submit">
</form>
