<!doctype html>

<html lang="en">

<head>

    <base href="/tiny-contact/">

    <title>tiny-contact</title>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="tiny-contact" />

    <link rel="stylesheet" href="ui/css/normalize.css">
    <link rel="stylesheet" href="ui/css/grid.css">
    <link rel="stylesheet" href="ui/css/main.css">

    <link rel="icon" href="ui/img/favicon.png">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="ui/js/scripts.js"></script>

</head>

<body>

    <div class="row">
        <div class="column grid_12">
            <h1><?= $headline['h1'] ?></h1>
            <h2><?= $headline['h2'] ?></h2>
            <hr>
        </div>
    </div>

    <div class="row">
        <?= $this->raw($content) ?>
    </div>

    <footer class="row">
        <div class="column grid_12">
            <a href="https://icons8.com">Icon pack by Icons8</a>
        </div>
    </footer>

</body>

</html>
